### ISSUE TITLE
Why can't i use a website address as a keyword?

### ISSUE THREAD

**Issue by nikolarN** [darsain/twitch-giveaways#10]
I tried using "www.trade.ninja" as a keyword for my giveaways and it used to work for a couple of days but right now it's not working.

Why is that?

**Comment by darsain** [comment]
I've tried to simulate it and it worked for me. Don't have resources (people) to try it in live chat though.

If it doesn't work it means twitch is changing the html of that particular message part? Or the messages with urls are getting filtered? Dunno. I'd have to see it live.

That being said, in the commit above I changed the way how message HTML is transformed into text that is being matched against the keyword. It could fix your issue. It also allows emoticons to be used as keywords :)

I'll publish the new version with this fix later today.

**Comment by darsain** [comment]
2.4.0 has been published. Report back if your issues is fixed.

**Comment by nikolarN** [comment]
Works properly now, awesome :D

**Comment by darsain** [comment]
Cool.
