### ISSUE TITLE
Announce the winner in chat

### ISSUE THREAD

**Issue by darsain** [darsain/twitch-giveaways#15]

**Comment by darsain** [comment]
I gave this 3 hours of frustration today and I'm giving up. Seems trivial to implement, but I was just not able to simulate a fucking `Enter` `keydown` event and dispatch it to chat textarea so it gets submitted.

My event listeners worked, but the twitch ember app was just ignoring every event sent to it. This made me hate front-end development like nothing else in a long time. I'm giving up here.

If anyone knows how to programatically send messages to twitch chat from a chrome extension (no access to page JS context, only DOM), let me know.

**Comment by bradgrafelman** [comment]
You say you have access to the DOM? Rather than simulating an Enter keypress, wouldn't it be easier to simulate a press of the "Chat" button?

For example, this jQuery code would send a message (but I'm not sure if this is what you mean by "no access to page JS context, only DOM" - suppose this could all be rewritten pretty easily to only use the DOM and not jQuery):

`$(".chat-interface textarea")[0].value = "Hello"; $(".primary")[0].click()`

**Comment by darsain** [comment]
Yes, firing the `#click()` method on Chat button works fine. Unfortunately there is no way how to identify that button explicitly, as its class is just a generic `button primary float-right`, so if they add another primary button floated to the right, the code might select and fire a bad action and cause issues for people.

I also thought about checking the `textContent` of the button against `Chat` string, but that will stop working when they add new languages for example.

Firing Enter on textarea seems to be the ideal and most robust solution here. Unfortunately that seems to be a sisyphean task...

> but I'm not sure if this is what you mean by "no access to page JS context

It means that extensions don't have access to the JS scope of the page, only the DOM (security reasons). For example, if twitch has jQuery on it's page, I can't use it. I need to include my own, because extension is running in its own clean context, where I don't have any jQuery included. Another example would be, if twitch defines `window.foo = 'bar'`, and I do `console.log(window.foo)` from extension context, I get undefined.

Also, raw JS please :) I'm not including monolithic libraries like jQuery. It would more than double the size of the app, only to use one method. Not happening.

**Comment by JabLuszko** [comment]
Looks twitch put proper classNames on Chat button - js-chat-buttons__submit looks good ;)
`<button class="button float-right qa-chat-buttons__submit js-chat-buttons__submit" data-ember-action="2286">
      Chat
    </button>`

**Comment by darsain** [comment]
Oh true, had to come with cheers changes. I'll look into it soon :)

**Comment by darsain** [comment]
HOLY HELL. It took me another 4 hours to implement this.

4 hours I was trying to figure out why `button.click()` doesn't work. Well guess what? It did. The whole time it worked, but it was behaving like it didn't, because twitch chat just silently fails if you try submitting the message with empty textarea.

The reason why twitch chat thought the textarea was empty was because it's an emberjs app, and its databinding works on `input` events, which are not fired if you change the textarea value programatically, i.e. doing `textarea.value = something;`. In fact, no event fires when that happens.

So I had to simulate an input event on textarea for the ember app to pick up the new value, and allow submission.

This was definitely also the reason why my `Enter` events weren't doing anything in my previous implementation attempt. So I'm 99% positive I don't need the submit button anymore. That I could just fire `Enter` keyboard event on textarea and it would work, but I've had enough of it today. `button.submit()` it is until it breaks.

**Comment by darsain** [comment]
So just to update the situation for completeness.

After #38 got implemented, It is now also possible to send messages directly through TMI interface as well. The code look like this:

```js
TMI._sessions[0]._connections.main._send('PRIVMSG #channel :Hello chat!');
```

I'm not using it though, because that sends the message silently, meaning the ember chat app won't display it. This would be a step backwards since people hitting the Roll button wouldn't see the announcement themselves, thinking it didn't happen.
