### ISSUE TITLE
Some entries not being validated...

### ISSUE THREAD

**Issue by victorguilhermeo** [darsain/twitch-giveaways#17]
I've come to realise that alot of entries are being left out from the giveaways.
This happens very often for some reason on channels with alot of active viewers, around... 1000 - 10000 active viewers.
I've tested myself a few times opening my own giveaway window and setting the same keyword as the streamer, but as soon as people start typing the keyword, when I do type too, my entry is not validated and my name doesnt appear on the giveaway users list on the left side.

Is there a way to fix this? Or prevent from happening.

**Comment by darsain** [comment]
This is intended. If you'd read the FAQ, you'd know that there are some people that are intentionaly ignored:

- everyone with a broadcaster badge
- logged in person that is running the giveaways

Reason is simple. You don't want to roll yourself.

**Comment by victorguilhermeo** [comment]
Im not saying I've try to enter the giveaway myself.
I did like this:
- I was on a channel of a big streamer, he had like 10.000 active viewers at that time.
- I wanted to see how many people were going to be on the giveaway, so I opened the Twitch Giveaway extension window.
- I typed the keyword in there, searched for my name on that imense list, it was there.

But the thing is, my friend who were on skype with me also typed the keyword, but somehow his name was not on the list, I dont know why.
There is a limit of entries before the system start glitching or anything?
Maybe its twitch lag? The chat was going insanely fast, might that be the reason?
PS: He was not banned/muted or anything from the chat.

**Comment by darsain** [comment]
He might have entered the keyword before *active timeout* kicked in. In other words, if *active timeout* is 5 minutes, and he entered the keyword 6 minutes ago, he is not on the list anymore.

**Comment by victorguilhermeo** [comment]
The standard active timeout that comes with the Giveaway Extension is 15 minutes right? I doubt the streamer changed it and if he did he wouldnt make it lower, but higher.

And besides, the streamer in question rolled the giveaway in 2 minutes, so I don't think he setted the timeout to less than that.

**Comment by darsain** [comment]
Yeah. Probably some messages not arriving in everyone's chat boxes. The extension parses messages that appear in the chat box, so if 2 open giveaways have different lists, it means their chat boxes failed to display all messages. Maybe one of them got disconnected for a few seconds or the way how twitch chat is designed means some messages won't arrive. Dunno.

**Comment by victorguilhermeo** [comment]
Hi darsain, I got a new suggestion for the giveaway extension.
You could make in a way that the extension cache the current chatters on
the stream (https://tmi.twitch.tv/group/user/CHANNELNAME/chatters) and only
picks those who are in the stream.
Since theres bots on twitch that are not required to be on chat to join
giveaways.

2015-08-30 10:01 GMT-03:00 darsain <notifications@github.com>:

**Comment by darsain** [comment]
This extension is in maintenance only mode. I'm not planning on adding any new features at this time. Can't justify the time investment.

**Comment by victorguilhermeo** [comment]
Your Twitch Giveaway extension is kinda broken, the bar layout is broken,
the Gift purple icon is covering up the entries.
Here is how it looks:

**Comment by achanceapps** [comment]
Here: [https://gyazo.com/6ea7232a81d930965abcd321a6f753bd](url)

**Comment by darsain** [comment]
User count has been fixed, Ill publish the new version sometimes today.
