### ISSUE TITLE
Youtube Gaming

### ISSUE THREAD

**Issue by ragnaroklow** [darsain/twitch-giveaways#19]
I'm a big github noob so I'm not sure if it's possible to send a private message. I was wondering if it would be possible make a version for Youtube? I absolutely loved your extension for twitch.

Have a nice day

**Comment by darsain** [comment]
Yes it would. But no I won't as I don't have time to donate right now, and there is no support coming in to justify taking time from stuff that pays the bills.

**Comment by darsain** [comment]
Gonna close this as It would be too much work for something I don't use.
