### ISSUE TITLE
Only notices whispers.

### ISSUE THREAD

**Issue by Curtis3321** [darsain/twitch-giveaways#21]
Hey,

So I just did a stream and wanted to do a giveaway but the only way they would get entered into the giveaway was if they /w to me. Other than that it wouldn't work.

Any advice?

**Comment by darsain** [comment]
No idea. Seems to work for everyone else. I'll close this until more reports with steps how to reproduce are submitted.

Also, check if some other twitch related extensions are not interfering with TGA.
