### ISSUE TITLE
[Feature Request] ServicePlatform

### ISSUE THREAD

**Issue by TheBaconSpace** [darsain/twitch-giveaways#25]
Would Love This Thing For [Beam](http:beam.pro/) and This is The [Dev Site](https://developer.beam.pro/) Thank You :blue_heart: :+1:

**Comment by darsain** [comment]
I don't have a free time to donate atm. I'm also not a user of this platform so I I don't think I'd do it even if I had any.

This extension itself is in maintenance mode only where I fix bugs here and there but that's about it.

**Comment by TheBaconSpace** [comment]
Wats This Bounty Thing all About This is New Stuff To Me Just The bounty
