### ISSUE TITLE
As a twitch streamer, I'd like to be able to restrict giveaways to followers only

### ISSUE THREAD

**Issue by Sebron** [darsain/twitch-giveaways#26]
To help non-partner streamers gain more followers, it would be nice to have an easily accessible check box to only include follower in the eligible category. This could also be added as a new "role" similar to Staff, Admin, etc..

**Comment by darsain** [comment]
I can't see who is follower beforehand. Need to make an API call for each user (unrealistic), or one giant API call for all followers (which takes forever and needs to be updated often). Unless something changed in recent moths. Dunno.

Also, the extension is atm in maintenance only mode, meaning I fix bugs here and there but I can't justify spending any significant time on this anymore. So no new features or reworks of current ones.

**Comment by darsain** [comment]
So I looked into it, and it's quite unrealistic for something of TGA's scope. If there was a follower badge displayed next to the names in chat, it would be trivial to parse it out along with subscriber/moderator badges, but as it is right now, I can't be making thousands of API requests. It would even be problematic to store that data somewhere. And take forever to load/update, as you can request 100 users at a time. For streamers with 100k followers, that's 10k requests...
