### ISSUE TITLE
Subscriber luck no longer works

### ISSUE THREAD

**Issue by rcmastermind** [darsain/twitch-giveaways#27]
Been using this for a while with no issues but for the last 10 days or so it doesn't seem to be pulling subscriber data which makes the Sub Luck no work. Please let me know if there is a way to fix. Thanks!

**Comment by darsain** [comment]
Yeah the badges are not being recognized. I'll look into it sometime in the next few days hopefully.

**Comment by darsain** [comment]
This is now fixed locally. I still have a few things to patch though. When that's done I'll publish new version later today. Hopefully :)
