### ISSUE TITLE
Compatibility with BTTV

### ISSUE THREAD

**Issue by victorguilhermeo** [darsain/twitch-giveaways#35]
As the title says, people type the keyword but dont get added to the list. I tested with BTTV and after BTTV modifies the chat structure it no longer adds people to the raffle list.

https://gyazo.com/d1316a5835765ed22b730b4d3040a883

**Comment by darsain** [comment]
Yes, BTTV breaking TGA parsing is a known issue that was wontfix until now, as I didn't have much time or motivation to maintain compatibility with Twich and BTTV at the same time.

But with recent sponsorship deals I can finally justify doing it, so I'll be looking into it soon.

**Comment by victorguilhermeo** [comment]
Oddly the extension used to roll people on version 2.5.0, but since the
recent update 2.5.1 it doesn't even roll anybody rendering it completely
useless.

2016-07-01 9:38 GMT-03:00 darsain <notifications@github.com>:

**Comment by darsain** [comment]
Just tested it to make sure, and it works fine. But I guess you are talking about your setup with BTTV? In which case yes, BTTV will break TGA.

Calling the extension useless because it can't account for other extensions interfering with it beforehand is quite harsh...

**Comment by victorguilhermeo** [comment]
May be, but the odd thing is, on v2.5.0 it used to work just fine, it was
adding people to the raffle list(with BTTV) just fine, yes, the sub badge
icon was buggy but still, at least it was working.
Alot of streamers are switching to the old version or using
nightbot's(which isn't that good but it works) giveaway page since the TGA
fully tilted.

2016-07-01 14:29 GMT-03:00 darsain <notifications@github.com>:

**Comment by victorguilhermeo** [comment]
Something that has changed on the last update completely broke the
extension, since the v2.5.0 that's all I can think.

2016-07-01 14:57 GMT-03:00 Victor Guilherme <victorguilhermeo@gmail.com>:

**Comment by victorguilhermeo** [comment]
Just checked again and noticed that TGA works but only for followers,
mods/subs etc don't get added to the list.

2016-07-01 14:58 GMT-03:00 Victor Guilherme <victorguilhermeo@gmail.com>:

**Comment by darsain** [comment]
I wanted to look into BTTV compatibility today, but all of my time was wasted on bugs while implementing Winner announcement feature in #15, so I'll have to put it aside for tomorrow.

I know that BTTV was probably a higher priority option, but I thought I'll just quickly deal with this trivial winner announcement thingy, and hop onto BTTV which should be more serious. At the end, it wasn't that trivial at all, but once I'm on an issue I have to finish it, so it wasted all of the time I had today :/

But, unless BTTV compatibility isn't gonna be unreasonably challenging bordering unrealistic to implement, it's definitely coming soon.

**Comment by victorguilhermeo** [comment]
Alright, thanks for the intel. Looking forward to see the new version. Good
luck with it man.

2016-07-01 20:00 GMT-03:00 darsain <notifications@github.com>:

**Comment by darsain** [comment]
Some update, I'm trying to get in contact with BTTV developer(s) to figure out the best way how to ensure future compatibility. The communication is slow though -.-

**Comment by darsain** [comment]
Good news everyone! BTTV compatibility is already implemented on my local copy. I have one more thing to deal with, but publishing it should happen within 24 hours.

The solution is just a temporary patch just so it works ASAP for you. The real more robust solution which'll ensure no more compatibility issues with other extensions now and in future will come later, as that will take longer to implement. If you are interested, you can subscribe to issue #38.

**Comment by darsain** [comment]
Published in 2.6.0

**Comment by victorguilhermeo** [comment]
Nice, it seems like its working fine now, the only thing that I found kinda
meh is the subluck even higher than it was before, not because of the luck
itself but because the slidebar became even wider and it makes harder to
slide it to 10 which is base for most of the streamers. But I can say
subluck on 100 is a little overkill, if a streamer wants to give even more
luck to subs they just set it on submode and make it sub only. I mean if it
was x20 it would be fine and the sliding bar wouldn't become so obnoxiously
wide.

2016-07-04 5:34 GMT-03:00 darsain <notifications@github.com>:

**Comment by victorguilhermeo** [comment]
If you still think that the subluck on 100 is mandatory I found another
solution for the issue which is to do something like this
https://gyazo.com/afbb674f8bcb6cce2d5a6bffb9ad4210 turn that <span> into an
<input> instead and link it to the slidebar's value, this way people can
just type rather than slide and avoid all that hassle. Perhaps you can ship
this update on the version where: "I'm also working on a small refactoring
to ensure it never breaks again.". Hopefully this was helpful.

**Comment by darsain** [comment]
Actually that's a recent bug introduced when I was changing semantics of options vs config. It should be 10. Gonna fix it now.

**Comment by darsain** [comment]
Fix published.

**Comment by victorguilhermeo** [comment]
Ohh, I see now, thanks @darsain, just want to point out that the new
"Announce winner" feature is golden, is pretty useful for streamers that
don't want to go through copying/pasting names.

2016-07-05 6:04 GMT-03:00 darsain <notifications@github.com>:
