### ISSUE TITLE
maxSubscriberLuck ended in config.js, rather than options.js, not used by ui/undefined.

### ISSUE THREAD

**Issue by JabLuszko** [darsain/twitch-giveaways#41]
Because it changed places it's not applied in main window and the range goes from 0 to undefined (aka 100 in UI).
in src/js/section/index.js you are using `max: ctrl.options.maxSubscriberLuck,`
in src/js/component/tga.js  you are using `self.config.maxSubscriberLuck`

It's in config.js at the moment, was in options.js few commits ago.
![image](https://cloud.githubusercontent.com/assets/1145742/16578691/329d8c6e-429c-11e6-9b6d-03907e02e355.png)

**Comment by darsain** [comment]
Yeah, I've JUST pushed the fix to webstore :) Thx for report tho.
