### ISSUE TITLE
Mods being withheld from raffles

### ISSUE THREAD

**Issue by T1ck27** [darsain/twitch-giveaways#42]
I open a new raffle, which is open to everyone. I see some mods type in the Keyword and it wont enter them in the raffle. I noticed and reset the raffle and same thing. I dont know what the issue is but any response would be greatly appreciated. 
Thanks,
Mike

**Comment by darsain** [comment]
I'll look into it tomorrow.

**Comment by T1ck27** [comment]
I don't know what happened it must have just been something going on yesterday but in my stream today it was fine. Actually had a mod win a raffle haha. Great work with this! Thanks for making it!

**Comment by darsain** [comment]
Oh cool, less work for me. Thx for updating the issue and not making me chase ghosts :)

What could've caused it is that TGA automatically ignores several types people:

- everyone with broadcaster badge (as why would you roll them?)
- person doing the giveaways (as why would you roll yourself?)
- everyone in *Settings > Ignore List*, which is by default populated with a lot of currently known twitch bots
