### ISSUE TITLE
Twitch Giveaways bugs on McLaughlingTv Channel.

### ISSUE THREAD

**Issue by McLaughling** [darsain/twitch-giveaways#47]
Hello; 

I got some bugs with Twitch Giveaways since I got the partnership on twitch.
I don't see viewers list when I'm starting a giveaway ; also if I'm using a keyword ! Si I 've got no idea how many viewers trying to win the Giveaway.
When I press "Roll" button, I don't see who won the giveaway on the plugin ; The only way to know that is to read it on the chat ! 

Thanks for reading my request ; 
Hope you understood my bad english !

**Comment by darsain** [comment]
Just tested it, and everything works fine. Proof: https://gfycat.com/HopefulFlawlessFrigatebird

So, unless you screenshot and describe the shit out of your issue, or record a video of what's happening, I'm clueless and can't help you.
