### ISSUE TITLE
Button sometimes doesn't load on channel page

### ISSUE THREAD

**Issue by daankk** [darsain/twitch-giveaways#9]
IT DOESNT WORK AT ALL ON CHROME

**Comment by darsain** [comment]
As far as I know the button doesn't show up when you open channel page directly, but does when you get there from other places like favorites or channels list.

It also shows up without an issue in popped out chats, so I suggest doing that in the meantime -> pop the chat out and use giveaways directly there. The button is in most cases just a proxy to the popped out chat anyway.

Dunno when I'll have some time to look at it.

And could you perhaps consider not being an ungrateful little brat and turn of that caps lock? thx :)

**Comment by daankk** [comment]
Hello, I apologize for caps. I got it to work and thank you for free software. Wasn't meant to offend you.

**Comment by darsain** [comment]
Fixed. Will be released in 2.4
